export const currencies = [
    {code: 'AED', symbol: 'د.إ',   name: 'United Arab Emirates dirham',                rate: 3.673104},
    {code: 'AFN', symbol: 'Af',    name: 'Afghan afghani',                             rate: 77.459504},
    {code: 'ALL', symbol: 'L',     name: 'Albanian lek',                               rate: 109.070403},
    {code: 'AMD', symbol: 'Դ',     name: 'Armenian dram',                              rate: 485.425041},
    {code: 'ANG', symbol: 'NAƒ',   name: 'Netherlands Antillean guilder',              rate: 1.86395},
    {code: 'AOA', symbol: 'Kz',    name: 'Angolan kwanza',                             rate: 318.106504},
    {code: 'ARS', symbol: '$',     name: 'Argentine peso',                             rate: 42.093041},
    {code: 'AUD', symbol: '$',     name: 'Australian dollar',                          rate: 1.394804},
    {code: 'AWG', symbol: 'ƒ',     name: 'Aruban Guilder/Florin',                      rate: 1.8},
    {code: 'AZN', symbol: 'ман',   name: 'Azerbaijani manat',                          rate: 1.705041},
    {code: 'BAM', symbol: 'КМ',    name: 'Bosnia and Herzegovina convertible mark',    rate: 1.727804},
    {code: 'BBD', symbol: '$',     name: 'Barbadian dollar',                           rate: 1.99045},
    {code: 'BDT', symbol: '৳',     name: 'Bangladeshi taka',                           rate: 84.048041},
    {code: 'BGN', symbol: 'лв',    name: 'Bulgarian lev',                              rate: 1.727804},
    {code: 'BHD', symbol: 'ب.د',   name: 'Bahraini dinar',                             rate: 0.37634},
    {code: 'BIF', symbol: '₣',     name: 'Burundian franc',                            rate: 1828.55},
    {code: 'BMD', symbol: '$',     name: 'Bermudian Dollar',                           rate: 1},
    {code: 'BND', symbol: '$',     name: 'Brunei dollar',                              rate: 1.353504},
    {code: 'BOB', symbol: 'Bs.',   name: 'Bolivian boliviano',                         rate: 6.906104},
    {code: 'BRL', symbol: 'R$',    name: 'Brazilian real',                             rate: 3.881904},
    {code: 'BSD', symbol: '$',     name: 'Bahamian dollar',                            rate: 0.99942},
    {code: 'BTC', symbol: '',      name: 'Bitcoin',                                    rate: 0.000197},
    {code: 'BTN', symbol: '',      name: 'Bhutanese ngultrum',                         rate: 69.235504},
    {code: 'BWP', symbol: 'P',     name: 'Botswana pula',                              rate: 10.565041},
    {code: 'BYN', symbol: 'Br',    name: 'Belarusian ruble',                           rate: 2.10355},
    {code: 'BYR', symbol: 'Br',    name: 'Belarusian ruble',                           rate: 19600},
    {code: 'BZD', symbol: '$',     name: 'Belize dollar',                              rate: 2.01455},
    {code: 'CAD', symbol: '$',     name: 'Canadian dollar',                            rate: 1.33355},
    {code: 'CDF', symbol: '₣',     name: 'Congolese franc',                            rate: 1636.000362},
    {code: 'CHF', symbol: '₣',     name: 'Swiss franc',                                rate: 1.00205},
    {code: 'CLF', symbol: '',      name: 'Unidad de Fomento',                          rate: 0.025048},
    {code: 'CLP', symbol: '$',     name: 'Chilean peso',                               rate: 663.530396},
    {code: 'CNY', symbol: '¥',     name: 'Chinese yuan',                               rate: 6.704204},
    {code: 'COP', symbol: '$',     name: 'Colombian peso',                             rate: 3118.75},
    {code: 'CRC', symbol: '₡',     name: 'Costa Rican colón',                          rate: 601.415041},
    {code: 'CUC', symbol: 'CUC$',  name: 'Cuban Convertible Peso',                     rate: 1},
    {code: 'CUP', symbol: '$',     name: 'Cuban peso',                                 rate: 26.5},
    {code: 'CVE', symbol: '$',     name: 'Cape Verdean escudo',                        rate: 97.41604},
    {code: 'CZK', symbol: 'Kč',    name: 'Czech koruna',                               rate: 22.668604},
    {code: 'DJF', symbol: '₣',     name: 'Djiboutian franc',                           rate: 177.720394},
    {code: 'DKK', symbol: 'kr',    name: 'Danish krone',                               rate: 6.606404},
    {code: 'DOP', symbol: '$',     name: 'Dominican peso',                             rate: 50.506504},
    {code: 'DZD', symbol: 'د.ج',   name: 'Algerian dinar',                             rate: 118.980393},
    {code: 'EGP', symbol: '£',     name: 'Egyptian pound',                             rate: 17.27904},
    {code: 'ERN', symbol: 'Nfk',   name: 'Eritrean nakfa',                             rate: 15.000358},
    {code: 'ETB', symbol: '',      name: 'Ethiopian birr',                             rate: 28.673504},
    {code: 'EUR', symbol: '€',     name: 'Euro',                                       rate: 0.88343},
    {code: 'FJD', symbol: '$',     name: 'Fijian dollar',                              rate: 2.137304},
    {code: 'FKP', symbol: '£',     name: 'Falkland Islands Pound',                     rate: 0.766204},
    {code: 'GBP', symbol: '£',     name: 'British pound',                              rate: 0.76435},
    {code: 'GEL', symbol: 'ლ',     name: 'Georgian lari',                              rate: 2.69504},
    {code: 'GGP', symbol: '',      name: 'Guernsey Pound',                             rate: 0.764475},
    {code: 'GHS', symbol: '₵',     name: 'Ghanaian cedi',                              rate: 5.22205},
    {code: 'GIP', symbol: '£',     name: 'Gibraltar Pound',                            rate: 0.764405},
    {code: 'GMD', symbol: 'D',     name: 'Gambian dalasi',                             rate: 49.49504},
    {code: 'GNF', symbol: '₣',     name: 'Guinean franc',                              rate: 9125.000355},
    {code: 'GTQ', symbol: 'Q',     name: 'Guatemala Quetzal',                          rate: 7.633304},
    {code: 'GYD', symbol: '$',     name: 'Guyanese dollar',                            rate: 209.16504},
    {code: 'HKD', symbol: '$',     name: 'Hong Kong Dollar',                           rate: 7.84295},
    {code: 'HNL', symbol: 'L',     name: 'Honduran lempira',                           rate: 24.429504},
    {code: 'HRK', symbol: 'Kn',    name: 'Croatian kuna',                              rate: 6.567804},
    {code: 'HTG', symbol: 'G',     name: 'Haitian gourde',                             rate: 84.691504},
    {code: 'HUF', symbol: 'Ft',    name: 'Hungarian forint',                           rate: 284.490388},
    {code: 'IDR', symbol: 'Rp',    name: 'Indonesian rupiah',                          rate: 14093},
    {code: 'ILS', symbol: '₪',     name: 'Israeli new shekel',                         rate: 3.56455},
    {code: 'IMP', symbol: '£',     name: 'Isle of Man Pound',                          rate: 0.764475},
    {code: 'INR', symbol: '₹',     name: 'Indian rupee',                               rate: 69.17104},
    {code: 'IQD', symbol: 'ع.د',   name: 'Iraqi dinar',                                rate: 1192.5},
    {code: 'IRR', symbol: '﷼',     name: 'Iranian rial',                               rate: 42105.000352},
    {code: 'ISK', symbol: 'Kr',    name: 'Icelandic króna',                            rate: 119.603816},
    {code: 'JEP', symbol: '£',     name: 'Jersey Pound',                               rate: 0.764475},
    {code: 'JMD', symbol: '$',     name: 'Jamaican dollar',                            rate: 129.060386},
    {code: 'JOD', symbol: 'د.ا',   name: 'Jordanian dinar',                            rate: 0.708504},
    {code: 'JPY', symbol: '¥',     name: 'Japanese yen',                               rate: 112.02504},
    {code: 'KES', symbol: 'Sh',    name: 'Kenyan shilling',                            rate: 101.000351},
    {code: 'KGS', symbol: '',      name: 'Kyrgyzstani som',                            rate: 69.84304},
    {code: 'KHR', symbol: '៛',     name: 'Cambodian riel',                             rate: 4038.850384},
    {code: 'KMF', symbol: '₣',     name: 'Comorian franc',                             rate: 435.375039},
    {code: 'KPW', symbol: '₩',     name: 'North Korean won',                           rate: 900.082431},
    {code: 'KRW', symbol: '₩',     name: 'South Korean won',                           rate: 1134.720384},
    {code: 'KWD', symbol: 'د.ك',   name: 'Kuwaiti dinar',                              rate: 0.30415},
    {code: 'KYD', symbol: '$',     name: 'Cayman Islands Dollar',                      rate: 0.832904},
    {code: 'KZT', symbol: '〒',    name: 'Kazakhstani tenge',                          rate: 379.270383},
    {code: 'LAK', symbol: '₭',     name: 'Lao kip',                                    rate: 8646.250383},
    {code: 'LBP', symbol: 'ل.ل',   name: 'Lebanese pound',                             rate: 1507.150382},
    {code: 'LKR', symbol: 'Rs',    name: 'Sri Lankan rupee',                           rate: 174.505039},
    {code: 'LRD', symbol: '$',     name: 'Liberian dollar',                            rate: 164.750382},
    {code: 'LSL', symbol: 'L',     name: 'Lesotho loti',                               rate: 13.940382},
    {code: 'LTL', symbol: 'Lt',    name: 'Lithuanian litas',                           rate: 2.95274},
    {code: 'LVL', symbol: 'Ls',    name: 'Latvian lats',                               rate: 0.60489},
    {code: 'LYD', symbol: 'ل.د',   name: 'Libyan dinar',                               rate: 1.389804},
    {code: 'MAD', symbol: 'د.م.',  name: 'Moroccan dirham',                            rate: 9.58875},
    {code: 'MDL', symbol: 'L',     name: 'Moldovan leu',                               rate: 17.665039},
    {code: 'MGA', symbol: '',      name: 'Malagasy ariary',                            rate: 3625.503758},
    {code: 'MKD', symbol: 'ден',   name: 'Macedonian denar',                           rate: 54.258504},
    {code: 'MMK', symbol: 'K',     name: 'Burmese kyat',                               rate: 1516.15038},
    {code: 'MNT', symbol: '₮',     name: 'Mongolian tögrög',                           rate: 2616.5},
    {code: 'MOP', symbol: 'P',     name: 'Macao Pataca',                               rate: 8.074304},
    {code: 'MRO', symbol: 'UM',    name: 'Mauritanian ouguiya',                        rate: 357.000346},
    {code: 'MUR', symbol: 'Rs',    name: 'Mauritian rupee',                            rate: 34.803743},
    {code: 'MVR', symbol: 'ރ.',    name: 'Maldivian rufiyaa',                          rate: 15.403741},
    {code: 'MWK', symbol: 'MK',    name: 'Malawian kwacha',                            rate: 733.895039},
    {code: 'MXN', symbol: '$',     name: 'Mexican peso',                               rate: 18.756604},
    {code: 'MYR', symbol: 'RM',    name: 'Malaysian ringgit',                          rate: 4.114504},
    {code: 'MZN', symbol: 'MTn',   name: 'Mozambican metical',                         rate: 64.250377},
    {code: 'NAD', symbol: '$',     name: 'Namibian dollar',                            rate: 13.960377},
    {code: 'NGN', symbol: '₦',     name: 'Nigerian naira',                             rate: 360.000344},
    {code: 'NIO', symbol: 'C$',    name: 'Nicaraguan córdoba',                         rate: 32.817039},
    {code: 'NOK', symbol: 'kr',    name: 'Norwegian krone',                            rate: 8.489204},
    {code: 'NPR', symbol: 'Rs',    name: 'Nepalese rupee',                             rate: 110.775039},
    {code: 'NZD', symbol: '$',     name: 'New Zealand dollar',                         rate: 1.47885},
    {code: 'OMR', symbol: 'ر.ع.',  name: 'Omani rial',                                 rate: 0.384265},
    {code: 'PAB', symbol: 'B/.',   name: 'Panamanian balboa',                          rate: 0.999515},
    {code: 'PEN', symbol: 'S/.',   name: 'Peruvian sol',                               rate: 3.29165},
    {code: 'PGK', symbol: 'K',     name: 'Papua New Guinean kina',                     rate: 3.379304},
    {code: 'PHP', symbol: '₱',     name: 'Philippine peso',                            rate: 51.669039},
    {code: 'PKR', symbol: 'Rs',    name: 'Pakistani rupee',                            rate: 141.595038},
    {code: 'PLN', symbol: 'zł',    name: 'Polish zloty',                               rate: 3.787504},
    {code: 'PYG', symbol: '₲',     name: 'Paraguayan guaraní',                         rate: 6208.050374},
    {code: 'QAR', symbol: 'ر.ق',   name: 'Qatari riyal',                               rate: 3.64125},
    {code: 'RON', symbol: 'L',     name: 'Romanian leu',                               rate: 4.210904},
    {code: 'RSD', symbol: 'din',   name: 'Serbian dinar',                              rate: 104.220373},
    {code: 'RUB', symbol: 'p.',    name: 'Russian ruble',                              rate: 64.320373},
    {code: 'RWF', symbol: '₣',     name: 'Rwandan franc',                              rate: 903.84},
    {code: 'SAR', symbol: 'ر.س',   name: 'Saudi riyal',                                rate: 3.74355},
    {code: 'SBD', symbol: '$',     name: 'Solomon Islands dollar',                     rate: 8.174304},
    {code: 'SCR', symbol: 'Rs',    name: 'Seychellois rupee',                          rate: 13.714504},
    {code: 'SDG', symbol: '£',     name: 'Sudanese pound',                             rate: 47.582504},
    {code: 'SEK', symbol: 'kr',    name: 'Swedish krona',                              rate: 9.269304},
    {code: 'SGD', symbol: '$',     name: 'Singapore dollar',                           rate: 1.352904},
    {code: 'SHP', symbol: '£',     name: 'Saint Helena Pound',                         rate: 1.320904},
    {code: 'SLL', symbol: 'Le',    name: 'Sierra Leonean leone',                       rate: 8700.000339},
    {code: 'SOS', symbol: 'Sh',    name: 'Somali shilling',                            rate: 580.000338},
    {code: 'SRD', symbol: '$',     name: 'Surinamese dollar',                          rate: 7.458038},
    {code: 'STD', symbol: 'Db',    name: 'São Tomé and Príncipe dobra',                rate: 21050.59961},
    {code: 'SVC', symbol: '$',     name: 'Salvadoran colón',                           rate: 8.74595},
    {code: 'SYP', symbol: 'ل.س',   name: 'Syrian pound',                               rate: 515.000338},
    {code: 'SZL', symbol: 'L',     name: 'Swazi lilangeni',                            rate: 13.96037},
    {code: 'THB', symbol: '฿',     name: 'Thai baht',                                  rate: 31.704038},
    {code: 'TJS', symbol: 'SM',    name: 'Tajikistani somoni',                         rate: 9.42445},
    {code: 'TMT', symbol: 'm',     name: 'Turkmenistan manat',                         rate: 3.51},
    {code: 'TND', symbol: 'د.ت',   name: 'Tunisian dinar',                             rate: 3.012504},
    {code: 'TOP', symbol: 'T$',    name: `Tongan pa'anga`,                             rate: 2.267404},
    {code: 'TRY', symbol: '₤',     name: 'Turkish lira',                               rate: 5.775504},
    {code: 'TTD', symbol: '$',     name: 'Trinidad and Tobago dollar',                 rate: 6.76725},
    {code: 'TWD', symbol: '$',     name: 'New Taiwan dollar',                          rate: 30.845038},
    {code: 'TZS', symbol: 'Sh',    name: 'Tanzanian shilling',                         rate: 2308.650368},
    {code: 'UAH', symbol: '',      name: 'Ukrainian hryvnia',                          rate: 26.713038},
    {code: 'UGX', symbol: 'Sh',    name: 'Ugandan shilling',                           rate: 3737.850367},
    {code: 'USD', symbol: '$',     name: 'United States dollar',                       rate: 1},
    {code: 'UYU', symbol: '$',     name: 'Uruguayan peso',                             rate: 33.896038},
    {code: 'UZS', symbol: '₴',     name: 'Uzbekistani som',                            rate: 8444.203624},
    {code: 'VEF', symbol: 'Bs F',  name: 'Venezuelan bolívar',                         rate: 9.987504},
    {code: 'VND', symbol: '₫',     name: 'Vietnamese dong',                            rate: 23186.55},
    {code: 'VUV', symbol: 'Vt',    name: 'Vanuatu vatu',                               rate: 112},
    {code: 'WST', symbol: 'T',     name: 'Samoan tala',                                rate: 2.613699},
    {code: 'XAF', symbol: '₣',     name: 'Central African CFA franc',                  rate: 579.503613},
    {code: 'XAG', symbol: '',      name: 'Silver Ounce',                               rate: 0.066736},
    {code: 'XAU', symbol: '',      name: 'Gold Ounce',                                 rate: 0.000775},
    {code: 'XCD', symbol: '$',     name: 'East Caribbean dollar',                      rate: 2.70255},
    {code: 'XDR', symbol: '',      name: 'Special drawing rights',                     rate: 0.71928},
    {code: 'XOF', symbol: '',      name: 'West African CFA franc',                     rate: 579.503602},
    {code: 'XPF', symbol: '₣',     name: 'CFP Franc',                                  rate: 105.360364},
    {code: 'YER', symbol: '﷼',     name: 'Yemeni rial',                                rate: 250.350364},
    {code: 'ZAR', symbol: 'R',     name: 'South African rand',                         rate: 13.955304},
    {code: 'ZMK', symbol: 'ZK',    name: 'Zambian Kwacha',                             rate: 9001.203593},
    {code: 'ZMW', symbol: 'ZK',    name: 'Zambian Kwacha',                             rate: 12.508037},
    {code: 'ZWL', symbol: '$',     name: 'Zimbabwe Dollar',                            rate: 322.355011}
]

export const currencyNames = currencies.map(cur => `${cur.name} (${cur.code})`);

export const getCurrencyFromName = (val) => {
  let res = currencies.filter(cur => `${cur.name} (${cur.code})` === val);
  return res[0];
}

export const convertCurrency = (amount, base, dest) => {
  return (amount / base.rate) * dest.rate;
}